name: lightning_api
description: Provices a Stream interface to the LeoFinance Lightning HTTP API.
version: 0.11.5
repository: https://github.com/LeoFinance/lightning-api

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  hive_api: ^0.4.0
  http: ^0.13.3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  rxdart: ^0.27.3
  scot_api: ^0.4.1

dev_dependencies:
  build_runner: ^2.1.2
  faker: ^2.0.0
  json_serializable: ^6.2.0
  mockito: ^5.1.0
  test: ^1.21.0
  very_good_analysis: ^2.4.0
